# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  BuildConfiguration: 'Release'
  DotNetVersion: '10.0.203'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '$(DotNetVersion)'

- script: |
    dotnet --info
  displayName: 'Display .NET Info'

